---

- name: Get all SASL users
  shell: "{{ argus_sasldblistusers_command }} | cut -f1 -d':'"
  register: register_sasldblistusers
  changed_when: false

- name: Delete SASL users
  shell: "{{ argus_saslpassword_command }} -a '{{ item.value.appname }}' -u '{{ item.value.domain }}' -d -f '{{ argus_sasldb_file }}' '{{ item.key }}'"
  with_dict: "{{ argus_sasl_user }}"
  when:
    - item.value.state == 'absent'
    - item.key ~ '@' ~ item.value.domain in register_sasldblistusers.stdout_lines

- name: Create SASL users
  shell: "echo -n {{ item.value.password }} | {{ argus_saslpassword_command }} -a '{{ item.value.appname }}' -u '{{ item.value.domain }}' -c -p -f '{{ argus_sasldb_file }}' {{ item.key }}"
  with_dict: "{{ argus_sasl_user }}"
  when:
    - item.value.state == 'present'
    - not item.key ~ '@' ~ item.value.domain in register_sasldblistusers.stdout_lines
