---
# tasks file for ansible-role-argus

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- include: "configure-{{ ansible_os_family }}.yml"

- include: "configure-sasl.yml"

- name: Create log directory
  file:
    path: "{{ argus_log_dir }}"
    mode: 0755
    owner: "{{ argus_user }}"
    group: "{{ argus_group }}"
    state: directory
  notify: Restart argus

- name: Create argus.conf
  template:
    src: argus.conf.j2
    dest: "{{ argus_conf_file }}"
    mode: 0644
    # validate: echo %s
  notify: Restart argus

- name: Start argus
  service:
    name: "{{ argus_service }}"
    enabled: true
    state: started
